# Generated by Django 6.0.6 on 2026-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Tank', 'Tank'), ('SP Gun', 'SP Gun'), ('Tank Destroyer', 'Tank Destroyer'), ('Armoured Half-Track', 'Armoured Half-Track'), ('Armoured Car', 'Armoured Car'), ('Carrier', 'Carrier'), ('Prime Mover', 'Prime Mover'), ('Truck', 'Truck'), ('Jeep', 'Jeep'), ('Motorcycle', 'Motorcycle')], max_length=20),
        ),
    ]
