# Generated by Django 6.0.6 on 2026-07-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammo',
            name='caliber_mm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
