# Generated by Django 6.0.6 on 2026-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='superstructure',
            name='mantlet_type_display',
            field=models.CharField(blank=True, choices=[('mantlet', 'Mantlet'), ('gun_shield', 'Gun Shield')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='superstructure',
            name='superstructure_type_display',
            field=models.CharField(choices=[('superstructure', 'Superstructure'), ('turret', 'Turret'), ('casemate', 'Casemate'), ('fighting_compartment', 'Fighting Compartment')], default='turret', max_length=25),
            preserve_default=False,
        ),
    ]
