# Generated by Django 6.0.6 on 2026-07-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_ammo_caliber_mm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammo',
            options={'verbose_name': 'Ammo', 'verbose_name_plural': 'Ammo'},
        ),
        migrations.AlterModelOptions(
            name='ammoballistics',
            options={'ordering': ['range_m'], 'verbose_name': 'Ammo Ballistics', 'verbose_name_plural': 'Ammo Ballistics'},
        ),
        migrations.AlterModelOptions(
            name='crewmember',
            options={'verbose_name': 'Crew Member', 'verbose_name_plural': 'Crew Members'},
        ),
        migrations.AlterModelOptions(
            name='hullarmour',
            options={'verbose_name': 'Hull Armour', 'verbose_name_plural': 'Hull Armour'},
        ),
        migrations.AlterModelOptions(
            name='hullstructure',
            options={'verbose_name': 'Hull Structure', 'verbose_name_plural': 'Hull Structures'},
        ),
        migrations.AlterModelOptions(
            name='superstructure',
            options={'verbose_name': 'Superstructure', 'verbose_name_plural': 'Superstructures'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicleammocapacity',
            options={'verbose_name': 'Vehicle Ammo Capacity', 'verbose_name_plural': 'Vehicle Ammo Capacities'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Weapon', 'verbose_name_plural': 'Weapons'},
        ),
        migrations.AlterModelOptions(
            name='weaponmount',
            options={'verbose_name': 'Weapon Mount', 'verbose_name_plural': 'Weapon Mounts'},
        ),
    ]
