# Generated by Django 6.0.6 on 2026-07-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_ammo_options_alter_ammoballistics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammo',
            options={'ordering': ['caliber_mm', 'nationality', 'name'], 'verbose_name': 'Ammo', 'verbose_name_plural': 'Ammo'},
        ),
    ]
