# Generated by Django 6.0.6 on 2026-07-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_superstructure_mantlet_type_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='ammo_type',
            field=models.CharField(choices=[('ap', 'Armour Piercing'), ('apcr', 'Armour Piercing, Composite Rigid'), ('he', 'High Explosive'), ('heat', 'High Explosive Anti-Tank'), ('ball', 'Standard small arms')], max_length=10),
        ),
    ]
