# Generated by Django 6.0.6 on 2026-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_ammo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammo',
            name='ammo_type',
            field=models.CharField(choices=[('ap', 'AP - Armour Piercing'), ('apcr', 'APCR - Armour Piercing, Composite Rigid (tungsten-cored)'), ('he', 'HE - High Explosive'), ('ball', 'BALL - Standard small arms')], max_length=10),
        ),
    ]
