# Generated by Django 6.0.6 on 2026-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_ammo_ammo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='general_info',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
