# Generated by Django 6.0.6 on 2026-07-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_ammo_ammo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['caliber_mm', 'nationality', 'name'], 'verbose_name': 'Weapon', 'verbose_name_plural': 'Weapons'},
        ),
    ]
