# Generated by Django 6.0.6 on 2026-07-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_weapon_general_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weapons/'),
        ),
    ]
