# Generated by Django 6.0.6 on 2026-07-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_weapon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HullWeaponMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main_armament', 'Main Armament'), ('secondary_armament', 'Secondary Armament'), ('coaxial_machine_gun', 'Coaxial Machine Gun'), ('bow_machine_gun', 'Bow Machine Gun'), ('pintle_machine_gun', 'Pintle Machine Gun')], max_length=20)),
                ('operated_by', models.CharField(choices=[('driver', 'Driver'), ('bow_gunner', 'Bow Gunner'), ('radio_operator', 'Radio Operator'), ('commander', 'Commander'), ('gunner', 'Gunner'), ('loader', 'Loader')], max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hull_weapon_mounts', to='vehicles.vehicle')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.weapon')),
            ],
            options={
                'verbose_name': 'Hull Weapon Mount',
                'verbose_name_plural': 'Hull Weapon Mounts',
            },
        ),
        migrations.CreateModel(
            name='SuperstructureWeaponMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main_armament', 'Main Armament'), ('secondary_armament', 'Secondary Armament'), ('coaxial_machine_gun', 'Coaxial Machine Gun'), ('bow_machine_gun', 'Bow Machine Gun'), ('pintle_machine_gun', 'Pintle Machine Gun')], max_length=20)),
                ('operated_by', models.CharField(choices=[('driver', 'Driver'), ('bow_gunner', 'Bow Gunner'), ('radio_operator', 'Radio Operator'), ('commander', 'Commander'), ('gunner', 'Gunner'), ('loader', 'Loader')], max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superstructure_weapon_mounts', to='vehicles.vehicle')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.weapon')),
            ],
            options={
                'verbose_name': 'Superstructure Weapon Mount',
                'verbose_name_plural': 'Superstructure Weapon Mounts',
            },
        ),
        migrations.DeleteModel(
            name='WeaponMount',
        ),
    ]
