# Generated by Django 6.0.6 on 2026-07-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_hullweaponmount_superstructureweaponmount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='hull',
        ),
        migrations.AddField(
            model_name='hullarmour',
            name='vehicle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hull_armour', to='vehicles.vehicle'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HullStructure',
        ),
    ]
