# Generated by Django 6.0.6 on 2026-07-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_vehicle_superstructure_vehicle_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='superstructure',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superstructure', to='vehicles.vehicle'),
        ),
    ]
