# Generated by Django 6.0.6 on 2026-07-14 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_remove_vehicle_vehicle_superstructure_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superstructure',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superstructure1', to='vehicles.vehicle'),
        ),
    ]
