# Generated by Django 6.0.6 on 2026-07-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_superstructure_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='available_from_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='available_from_year',
            field=models.PositiveSmallIntegerField(choices=[(1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945')], default=1939, verbose_name='available from year (1915 - 1945)'),
        ),
    ]
